"""add sanctions and is_admin

Revision ID: 4d63c3abb3c1
Revises: b9d27b85e65f
Create Date: 2026-05-22 11:08:34.266171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d63c3abb3c1'
down_revision: Union[str, Sequence[str], None] = 'b9d27b85e65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WARNING', 'SUSPENSION', 'BAN', name='sanctiontype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_id'), 'sanctions', ['id'], unique=False)
    op.create_index(op.f('ix_sanctions_user_id'), 'sanctions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_sanctions_user_id'), table_name='sanctions')
    op.drop_index(op.f('ix_sanctions_id'), table_name='sanctions')
    op.drop_table('sanctions')
    # ### end Alembic commands ###
