"""add avatar column to users

Revision ID: acc098756a6c
Revises: 4d63c3abb3c1
Create Date: 2026-05-26 19:02:27.452279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc098756a6c'
down_revision: Union[str, Sequence[str], None] = '4d63c3abb3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=10), nullable=True))
    op.execute("UPDATE users SET avatar = '🐱' WHERE avatar IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
